from modules.adb import ADB
from modules.executor import CMD
from modules.automator import Auto
from modules.base_module import BaseClass
from modules.play_store import PlayStore
from modules.twitter import Twitter
from modules.spotify import Spotify
from modules.twitch import Twitch
from modules.proxy import OXY
